# Generated by Django 5.0 on 2023-12-09 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Doctors',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_phone', models.CharField(max_length=255)),
                ('p_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField(auto_now=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctors')),
            ],
        ),
    ]
